const LEFT_SAFE_INTEGER = Number.MIN_SAFE_INTEGER
const RIGHT_SAFE_INTEGER = Number.MAX_SAFE_INTEGER
const SCALE_DEPTH_LOG2_NATURAL = Math.log2(RIGHT_SAFE_INTEGER)
const SCALE_DEPTH_LOG2_REAL = 2 * SCALE_DEPTH_LOG2_NATURAL
const SCALE_DEPTH_LOG2_MIN_VALUE = - Math.log2(Number.MIN_VALUE)

const AtomConst = {
  PRECISION: 6,
  LEFT_INFINITY: -Infinity,
  RIGHT_INFINITY: Infinity,
  LEFT_SAFE_INTEGER,
  RIGHT_SAFE_INTEGER,
  DISTANCE_RATIO_HALF: 0.5,
  DISTANCE_STEP_ONE: 1,
  SCALE_DEPTH_LOG2_NATURAL,
  SCALE_DEPTH_LOG2_REAL,
  SCALE_DEPTH_LOG2_MIN_VALUE,
  SCALE_DEPTH_LOG2: SCALE_DEPTH_LOG2_NATURAL + SCALE_DEPTH_LOG2_MIN_VALUE,
  NEIGHBOR_COLLISION_ERROR: new Error(`Neighbor collision!`)
}

module.exports = AtomConst
